=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-cmd.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ELEMENT CODE (#PCDATA)>
<!ELEMENT CRET (#PCDATA)>
<!ELEMENT MSG (#PCDATA)>
<!ELEMENT NOROWS (#PCDATA)>
<!ELEMENT OBJECT (#PCDATA)>
<!ELEMENT SQL (#PCDATA)>
<!ELEMENT SQLCMD (OBJECT, SQL, NOROWS, CRET)>
<!ATTLIST SQLCMD
	version CDATA #REQUIRED
>
<!ELEMENT STATUS (CODE, MSG)>
<!ELEMENT TRAVELDB (STATUS, SQLCMD)>
<!ATTLIST TRAVELDB
	version CDATA #REQUIRED
>

=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-cmd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited martin@yafra.org -->
<!DOCTYPE TRAVELDB SYSTEM "G:\work\cvswork\mapo\xml\tdb-cmd.dtd">
<TRAVELDB version="1.0">
	<STATUS>
		<CODE>0</CODE>
		<MSG>OK</MSG>
	</STATUS>
	<SQLCMD version="1.0">
		<OBJECT>250</OBJECT>
		<SQL>DELETE * FROM ROOT.SAISON</SQL>
		<NOROWS>3</NOROWS>
		<CRET>0</CRET>
	</SQLCMD>
</TRAVELDB>
