=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-query.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ELEMENT CODE (#PCDATA)>
<!ELEMENT CRET (#PCDATA)>
<!ELEMENT HEADER (OBJECT, SQL, NOROWS, NOFIELDS, CRET)>
<!ELEMENT MSG (#PCDATA)>
<!ELEMENT NOFIELDS (#PCDATA)>
<!ELEMENT NOROWS (#PCDATA)>
<!ELEMENT OBJECT (#PCDATA)>
<!ELEMENT QUERY (HEADER, RECORDS)>
<!ATTLIST QUERY
	version CDATA #REQUIRED
>
<!ELEMENT RECORD (bez, code, text)>
<!ATTLIST RECORD
	id (1 | 2 | 3) #REQUIRED
>
<!ELEMENT RECORDS (RECORD+)>
<!ELEMENT SQL (#PCDATA)>
<!ELEMENT STATUS (CODE, MSG)>
<!ELEMENT TRAVELDB (STATUS, QUERY)>
<!ATTLIST TRAVELDB
	version CDATA #REQUIRED
>
<!ELEMENT bez (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-query.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited martin@yafra.org -->
<!DOCTYPE TRAVELDB SYSTEM "G:\work\cvswork\mapo\xml\tdb-query.dtd">
<TRAVELDB version="1.0">
	<STATUS>
		<CODE>0</CODE>
		<MSG>OK</MSG>
	</STATUS>
	<QUERY version="1.0">
		<HEADER>
			<OBJECT>250</OBJECT>
			<SQL>SELECT * FROM ROOT.SAISON</SQL>
			<NOROWS>3</NOROWS>
			<NOFIELDS>4</NOFIELDS>
			<CRET>0</CRET>
		</HEADER>
		<RECORDS>
			<RECORD id="1">
				<bez>Exterior Dimensions</bez>
				<code>exterior.gif</code>
				<text>fasddf</text>
			</RECORD>
			<RECORD id="2">
				<bez>Interior Design</bez>
				<code>interior.gif</code>
				<text>fsafa</text>
			</RECORD>
			<RECORD id="3">
				<bez>bla</bez>
				<code>blo</code>
				<text>blu</text>
			</RECORD>
		</RECORDS>
	</QUERY>
</TRAVELDB>
