=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-login.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ELEMENT BCHST (#PCDATA)>
<!ATTLIST BCHST
	ID CDATA #REQUIRED
>
<!ELEMENT CLIENTHOSTNAME (#PCDATA)>
<!ELEMENT CODE (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ATTLIST COUNTRY
	ID CDATA #REQUIRED
>
<!ELEMENT DBNAME (#PCDATA)>
<!ELEMENT DLAT (#PCDATA)>
<!ATTLIST DLAT
	ID CDATA #REQUIRED
>
<!ELEMENT DLNT (#PCDATA)>
<!ATTLIST DLNT
	ID CDATA #REQUIRED
>
<!ELEMENT DLT (#PCDATA)>
<!ATTLIST DLT
	ID CDATA #REQUIRED
>
<!ELEMENT DLTT (#PCDATA)>
<!ATTLIST DLTT
	ID CDATA #REQUIRED
>
<!ELEMENT ENDTIME (#PCDATA)>
<!ELEMENT FLAG (#PCDATA)>
<!ELEMENT KAT (#PCDATA)>
<!ATTLIST KAT
	ID CDATA #REQUIRED
>
<!ELEMENT LANG (#PCDATA)>
<!ATTLIST LANG
	ID CDATA #REQUIRED
>
<!ELEMENT LOGIN (DBNAME, USER, PWD, CLIENTHOSTNAME, FLAG, UID, BCHST, SECLEVEL, LANG, COUNTRY, DLTT, DLT, KAT, DLAT, DLNT, SAI, PRG, STARTTIME, ENDTIME, RANGE)>
<!ATTLIST LOGIN
	version CDATA #REQUIRED
>
<!ELEMENT MSG (#PCDATA)>
<!ELEMENT PRG (#PCDATA)>
<!ATTLIST PRG
	ID CDATA #REQUIRED
>
<!ELEMENT PWD (#PCDATA)>
<!ELEMENT RANGE (#PCDATA)>
<!ELEMENT SAI (#PCDATA)>
<!ATTLIST SAI
	ID CDATA #REQUIRED
>
<!ELEMENT SECLEVEL (#PCDATA)>
<!ATTLIST SECLEVEL
	ID CDATA #REQUIRED
>
<!ELEMENT STARTTIME (#PCDATA)>
<!ELEMENT STATUS (CODE, MSG)>
<!ELEMENT TRAVELDB (STATUS, LOGIN)>
<!ATTLIST TRAVELDB
	version CDATA #REQUIRED
>
<!ELEMENT UID (#PCDATA)>
<!ELEMENT USER (#PCDATA)>

=== yafraorg/yafra-tdb-c/org.yafra.tdb.setup/config/xml/tdb-login.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited martin@yafra.org -->
<!DOCTYPE TRAVELDB SYSTEM "G:\work\cvswork\mapo\xml\tdb-login.dtd">
<TRAVELDB version="1.0">
	<STATUS>
		<CODE>0</CODE>
		<MSG>OK</MSG>
	</STATUS>
	<LOGIN version="1.0">
		<DBNAME>mapo</DBNAME>
		<USER>mwn</USER>
		<PWD>mwn</PWD>
		<CLIENTHOSTNAME>webpc</CLIENTHOSTNAME>
		<FLAG>1</FLAG>
		<UID>1</UID>
		<BCHST ID="-1">Alpha</BCHST>
		<SECLEVEL ID="1">Admin</SECLEVEL>
		<LANG ID="-1">German</LANG>
		<COUNTRY ID="-1">Switzerland</COUNTRY>
		<DLTT ID="-1">Schiff</DLTT>
		<DLT ID="-1">Aria</DLT>
		<KAT ID="-1">Basic</KAT>
		<DLAT ID="-1">Schiffreise</DLAT>
		<DLNT ID="-1">Erwachsene</DLNT>
		<SAI ID="-1">Sommer 2004</SAI>
		<PRG ID="-1">USA</PRG>
		<STARTTIME>-1</STARTTIME>
		<ENDTIME>-1</ENDTIME>
		<RANGE>0</RANGE>
	</LOGIN>
</TRAVELDB>
